---
# tasks file for st2web

- name: Add nginx key
  become: yes
  become_method: sudo
  apt_key:
    url: http://nginx.org/keys/nginx_signing.key
    state: present

- name: Add nginx repos
  become: yes
  become_method: sudo
  apt_repository:
    repo: "deb http://nginx.org/packages/ubuntu/ trusty nginx"
    state: present
    update_cache: yes

- name: Install nginx
  become: yes
  become_method: sudo
  apt:
    name: nginx=1.8.*
    state: present

- name: Install latest st2web package
  become: yes
  become_method: sudo
  apt:
    name: st2web
    state: latest
  when: st2_version == "stable"
  notify:
    - restart st2

- name: Install exact st2web package
  become: yes
  become_method: sudo
  apt:
    name: st2web={{ st2_version }}-{{ st2web_revision }}
    state: present
  when: st2_version != "stable"
  notify:
    - restart st2

- name: Create ssl cert dir
  become: yes
  become_method: sudo
  file:
    state: directory
    dest: /etc/ssl/st2

- name: Create ssl cert
  become: yes
  become_method: sudo
  shell: openssl req -x509 -newkey rsa:2048 -keyout /etc/ssl/st2/st2.key -out /etc/ssl/st2/st2.crt -days 365 -nodes -subj "/C=US/ST=California/L=Palo Alto/O=StackStorm/OU=Information Technology/CN=$(hostname)"
  args:
    creates: /etc/ssl/st2/st2.key
  notify:
    - Restart nginx

- name: Remove default site
  become: yes
  become_method: sudo
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Create nginx folders
  become: yes
  become_method: sudo
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - /etc/nginx/sites-available/
    - /etc/nginx/sites-enabled/

- name: Ensure site-available is loaded
  become: yes
  become_method: sudo
  lineinfile:
    state: present
    dest: /etc/nginx/nginx.conf
    regexp: 'include /etc/nginx/sites-enabled/'
    insertafter: '    include /etc/nginx/conf.d/'
    line: 'include /etc/nginx/sites-enabled/*;'

- name: Copy Nginx config
  become: yes
  become_method: sudo
  command: cp /usr/share/doc/st2/conf/nginx/st2.conf /etc/nginx/sites-available/
  args:
    creates: /etc/nginx/sites-available/st2.conf
  notify:
    - Restart nginx

- name: Enable site
  become: yes
  become_method: sudo
  file:
    state: link
    src: /etc/nginx/sites-available/st2.conf
    dest: /etc/nginx/sites-enabled/st2.conf
  notify:
    - Restart nginx
