---

arteria_runfolder_env_root: /opt/arteria/arteria-runfolder-env
arteria_runfolder_config_root: /etc/arteria/runfolder
arteria_runfolder_app_config: "{{ arteria_runfolder_config_root }}/app.config"
arteria_runfolder_logger_config: "{{ arteria_runfolder_config_root }}/logger.config"
arteria_runfolder_supervisord_config: /etc/supervisor/conf.d/runfolder.conf
runfolder_path: "/data/{{ ansible_hostname }}/runfolders"
runfolder_ws: runfolder-ws

arteria_incoming_config_root: /etc/arteria/incoming-runfolder
arteria_incoming_app_config: "{{ arteria_incoming_config_root }}/app.config"
arteria_incoming_logger_config: "{{ arteria_incoming_config_root }}/logger.config"
arteria_incoming_supervisord_config: /etc/supervisor/conf.d/incoming-runfolder.conf
incoming_path: "/data/{{ ansible_hostname }}/incoming"
incoming_ws: incoming-ws

# By default, fetch sources from a git repo. Change this to "mount" to
# fetch from a repo mounted at /arteria
arteria_runfolder_sources: git
arteria_runfolder_repo: https://github.com/arteria-project/arteria-runfolder.git
arteria_runfolder_version: v1.1.0
