---

#arteria_environment: staging
arteria_environment: dev

send_mail_from: mail@from
send_mail_to: mail@to

bcl2fastq_service_port: 10900
siswrap_service_port: 10700
runfolder_service_port: 10800

arteria_user: arteria
arteria_uid: 4242
arteria_group: arteria
arteria_gid: 4242

arteria_sisyphus_user: arteria
summary_host_user: [remote linux user]
remote_host_user: [remote linux user]
irma_host_user: [remote linux user]
