---

arteria_user: arteria
arteria_uid: 4242
arteria_group: arteria
arteria_gid: 4242

# Default to "prod". If set to "staging" or "dev" some roles might have a slightly different
# behavior, enabling debug mode and allowing extra integration tests capabilities.
arteria_environment: prod

