---

st2_version: 2.0.1
st2_revision: 3
st2web_revision: 2
mistral_version: 2.0.1-3

st2_system_user: arteria
st2_system_user_in_sudoers: no

hermes_base_url: [url to staging version of samplesheet webservice]
hermes_user: [cleartext username]

summary_host: [hostname to host where statistics are kept]
summary_destination: [path on host where we store statistics from testing]

# TODO: Fix this better later when needed again. Doesn't work now. 
remote_host: testuppmax
remote_destination: [remote path for test of runfolders]

postgresql_logging_collector: on
postgresql_log_directory: /var/log/postgresql

remote_sisyphus_location: [remote path to sisyphus sw]

#arteria_environment: staging
arteria_environment: dev

send_mail_from: mail@from
send_mail_to: mail@to

bcl2fastq_service_port: 10900
siswrap_service_port: 10700
runfolder_service_port: 10800

arteria_user: arteria
arteria_uid: 4242
arteria_group: arteria
arteria_gid: 4242

arteria_sisyphus_user: arteria
summary_host_user: [linux user]
remote_host_user: [linux user]
irma_host_user: [linux user]
